{
    "success": True,
    "results": [
        {"tool_name": "sensor_history", "success": False, "error": "Unsupported tool"},
        {"tool_name": "sensor_history", "success": False, "error": "Unsupported tool"},
        {"tool_name": "sensor_history", "success": False, "error": "Unsupported tool"},
        {
            "tool_name": "camera_analysis_history",
            "success": False,
            "error": "Unsupported tool",
        },
        {
            "tool_name": "camera_analysis_history",
            "success": False,
            "error": "Unsupported tool",
        },
        {
            "tool_name": "daily_farm_schedule",
            "success": True,
            "result": {
                "schedule_count": 0,
                "global": [],
                "level_1": [],
                "level_2": [],
                "schedule": [],
            },
        },
        {
            "tool_name": "pending_recommendations",
            "success": False,
            "error": "could not determine data type of parameter $1",
        },
        {
            "tool_name": "pending_approvals",
            "success": False,
            "error": "could not determine data type of parameter $1",
        },
    ],
}


{
    "success": True,
    "results": [
        {
            "tool_name": "daily_farm_schedule",
            "success": True,
            "result": {
                "schedule_count": 0,
                "global": [],
                "level_1": [],
                "level_2": [],
                "schedule": [],
            },
        },
        {
            "tool_name": "sensor_history",
            "success": True,
            "result": {
                "sensor_type": "ph",
                "start_time": "2026-09-14T06:59:57.237082+00:00",
                "end_time": "2026-09-15T06:59:57.237082+00:00",
                "bucket_size": "30 minutes",
                "summary": {
                    "start_value": None,
                    "end_value": None,
                    "average": None,
                    "median": None,
                    "minimum": None,
                    "maximum": None,
                    "standard_deviation": None,
                    "sample_count": 0,
                    "valid_count": 0,
                    "suspect_count": 0,
                    "invalid_count": 0,
                    "valid_percentage": 0,
                },
                "trend": {
                    "direction": "INSUFFICIENT_DATA",
                    "change": None,
                    "slope_per_bucket": None,
                    "persistent": False,
                },
                "anomalies": {"isolated_spike_count": 0},
                "timeline": [],
            },
        },
        {
            "tool_name": "sensor_history",
            "success": True,
            "result": {
                "sensor_type": "ec",
                "start_time": "2026-09-14T06:59:57.237401+00:00",
                "end_time": "2026-09-15T06:59:57.237401+00:00",
                "bucket_size": "30 minutes",
                "summary": {
                    "start_value": None,
                    "end_value": None,
                    "average": None,
                    "median": None,
                    "minimum": None,
                    "maximum": None,
                    "standard_deviation": None,
                    "sample_count": 0,
                    "valid_count": 0,
                    "suspect_count": 0,
                    "invalid_count": 0,
                    "valid_percentage": 0,
                },
                "trend": {
                    "direction": "INSUFFICIENT_DATA",
                    "change": None,
                    "slope_per_bucket": None,
                    "persistent": False,
                },
                "anomalies": {"isolated_spike_count": 0},
                "timeline": [],
            },
        },
        {
            "tool_name": "sensor_history",
            "success": True,
            "result": {
                "sensor_type": "water_temperature",
                "start_time": "2026-09-14T06:59:57.237708+00:00",
                "end_time": "2026-09-15T06:59:57.237708+00:00",
                "bucket_size": "30 minutes",
                "summary": {
                    "start_value": None,
                    "end_value": None,
                    "average": None,
                    "median": None,
                    "minimum": None,
                    "maximum": None,
                    "standard_deviation": None,
                    "sample_count": 0,
                    "valid_count": 0,
                    "suspect_count": 0,
                    "invalid_count": 0,
                    "valid_percentage": 0,
                },
                "trend": {
                    "direction": "INSUFFICIENT_DATA",
                    "change": None,
                    "slope_per_bucket": None,
                    "persistent": False,
                },
                "anomalies": {"isolated_spike_count": 0},
                "timeline": [],
            },
        },
        {
            "tool_name": "camera_analysis_history",
            "success": True,
            "result": {
                "level_no": 1,
                "start_time": "2026-09-14T06:59:57.237953+00:00",
                "end_time": "2026-09-15T06:59:57.237953+00:00",
                "time_range": "24h",
                "bucket_size": "1 hour",
                "summary": {
                    "camera_count": 3,
                    "hour_count": 0,
                    "analysis_count": 0,
                    "complete_hour_count": 0,
                    "incomplete_hour_count": 0,
                    "cameras_without_analysis": [
                        {"camera_id": 5, "camera_name": "cam1"},
                        {"camera_id": 6, "camera_name": "cam2"},
                        {"camera_id": 7, "camera_name": "cam3"},
                    ],
                },
                "timeline": [],
            },
        },
        {
            "tool_name": "camera_analysis_history",
            "success": True,
            "result": {
                "level_no": 2,
                "start_time": "2026-09-14T06:59:57.238079+00:00",
                "end_time": "2026-09-15T06:59:57.238079+00:00",
                "time_range": "24h",
                "bucket_size": "1 hour",
                "summary": {
                    "camera_count": 1,
                    "hour_count": 0,
                    "analysis_count": 0,
                    "complete_hour_count": 0,
                    "incomplete_hour_count": 0,
                    "cameras_without_analysis": [
                        {"camera_id": 8, "camera_name": "cam4"}
                    ],
                },
                "timeline": [],
            },
        },
    ],
}


